apiVersion: v1
kind: Service
metadata:
  name: {{ include "json-rpc-relay.fullname" . }}
  labels:
    {{- include "json-rpc-relay.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
# This addes support for an NEG setup where the key is a string but the value is JSON
{{- if .Values.service.annotations_NEG }}
  annotations:
{{- range  $key, $value := .Values.service.annotations_NEG }}
    {{ $key }}: {{ toJson $value }}
{{- end }}      
{{- end }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.name  }}
      protocol: TCP
      name: {{ .Values.ports.name  }}
  selector:
    app: {{ template "json-rpc-relay.name" . }}
    {{- include "json-rpc-relay.selectorLabels" . | nindent 4 }}
